name: Build and deploy to Kintone instance

on:
  push:
    tags:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build

    - name: Upload to Kintone ${{ vars.KINTONE_BASE_URL }}
      run: kintone-customize-uploader customize-manifest.json --base-url ${{ vars.KINTONE_BASE_URL }} --username ${{ secrets.KINTONE_USERNAME}} --password ${{ secrets.KINTONE_PASSWORD}}
