name: Check eslint and dependencies license

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'caongocthien/bulk-status-update1'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      
    - name: Install dependencies
      run: npm install
      
    - name: Run ESLint
      run: npx eslint . --ext .js --max-warnings 1

    - name: Check License
      
      uses: caongocthien/check-license@1.0.2
      with:
        licenses: 'MIT'

    - name: Check License 1
      if: github.repository == 'caongocthien/bulk-status-update'
      run: echo "thien ngo cao"

