name: Check code

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
      
    - name: Run ESLint
      run: npx eslint . --ext .js --max-warnings 0

    - name: Action log
      uses: caongocthien/action@v1.0.2
      with:
        message: 'Hello, World!'
