name: CI Workflow

on:
  push:
    branches:
      - develop
      - staging
      - main
  pull_request:
    branches:
      - develop

jobs:
  build:
    environment: QA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Check node
        run: node -v
