# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI action

on:
  pull_request:
    branches:
      - main



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
      
    - name: Run ESLint
      run: npx eslint . --ext .js --max-warnings 0

    - name: Build
      run: npm run build

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: customization_built
        path: dest/desktop/js/main.js

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download math result for job 2
      uses: actions/download-artifact@v4
      with:
        name: customization_built
        path: build/download

    - name: List
      run: ls
        
    - uses: shallwefootball/s3-upload-action@master
      name: Upload S3
      id: S3
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: build/download/main.js
    
