name: Scheduled Workflow

on:
  schedule:
    - cron: "25 15 * * *"
  push:
    branches:
      - main

# * * * * *
# | | | | |
# | | | | +---- Day of the week (0 - 7) (Sunday=0 or 7)
# | | | +------ Month (1 - 12)
# | | +-------- Day of the month (1 - 31)
# | +---------- Hour (0 - 23)
# +------------ Minute (0 - 59)

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:

    - name: Run a script
      run: echo $(date +"%Y-%m-%d %H:%M:%S")
